version: '3'

services:
  backend:
    build: 
      context: ./
      dockerfile: Dockerfile
    image: puru21/BIA:0.0.1
    container_name: BIA-container
    ports:
      - "8000:8000"
    volumes:
      - ./ :/backend

    command: "python manage.py runserver 0.0.0.0:8000"
