version: '3'

services:
  backend:
    build: 
      context: ./
      dockerfile: Dockerfile
    image: puru21/bia:0.0.2
    container_name: bia-container
    ports:
      - "8000:8000"
    volumes:
      - .:/backend

    command: "python manage.py runserver 0.0.0.0:8000"
